version: "3.3"

services:
  web-server:
    build: .
    restart: always
    environment:
      WEBSRV_APP_DIR: /app
      WEBSRV_URLGEN_DIR: /srv/urlgen
      MYSQL_ROOT_PASSWORD:
    depends_on:
      - db
    ports:
      - "80:8080"
    networks:
      - radio
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: bind
        source: ./urlgen/dat
        target: /srv/urlgen

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    networks:
      radio:
        aliases:
          - database
    volumes:
      # mount our init scripts
      - ./db:/docker-entrypoint-initdb.d

networks:
  radio:

volumes:
  database-data:
