version: "3.3"

services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile-websrv
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "80:8080"
    depends_on:
      - db
    networks:
      - radio
    volumes:
      - type: volume
        source: songs
        target: /songs

  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
    networks:
      - radio
    volumes:
      - type: volume
        source: data
        target: /var/lib/mysql

networks:
  radio:

volumes:
  data:
  songs:
