version: '3.2'

services:
  web-server:
    build: ./websrv
    restart: always
    depends_on:
      - db
    ports:
      - "80:8080"
    networks:
      - radio
    volumes:
      - type: bind
        source: ./app
        target: /app/app

  db:
    image: mysql:5.7
    restart: always
    env_file: ./filedb/db.env
    networks:
      radio:
        aliases:
          - database
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql

networks:
  radio:

volumes:
  database-data:
